# Generated by Django 4.1.5 on 2023-01-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('webvpn_key', models.CharField(max_length=512, verbose_name='_webvpn_key')),
                ('exp_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.token')),
            ],
        ),
    ]
