# Generated by Django 4.1.5 on 2023-02-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='cookie_text',
            field=models.TextField(default='[]'),
        ),
    ]
